# Generated by Django 5.0.1 on 2024-11-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationcluster',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stationcluster',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='stationcluster',
            name='update_marker',
        ),
    ]
