# Generated by Django 5.0.1 on 2024-11-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0002_remove_stationcluster_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='restriction_code',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='update_marker',
        ),
        migrations.AlterField(
            model_name='fare',
            name='restriction_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='railbrowser.restriction'),
        ),
    ]
