# Generated by Django 5.0.1 on 2024-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0003_remove_flow_record_type_remove_flow_restriction_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='restriction_code',
        ),
        migrations.RemoveField(
            model_name='fare',
            name='update_marker',
        ),
        migrations.AlterField(
            model_name='fare',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
