# Generated by Django 5.0.1 on 2024-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0004_remove_fare_restriction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='restriction_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fare',
            name='ticket_code',
            field=models.CharField(max_length=3),
        ),
    ]
