# Generated by Django 5.0.1 on 2024-11-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0005_fare_restriction_code_alter_fare_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='railbrowser.tickettype'),
            preserve_default=False,
        ),
    ]
