# Generated by Django 5.0.1 on 2024-11-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0006_fare_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='ticket_code',
        ),
    ]
