# Generated by Django 5.1.3 on 2024-11-17 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('railbrowser', '0007_remove_fare_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='destination_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_flows', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='destination_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
