# Generated by Django 5.1.3 on 2024-11-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('railbrowser', '0008_alter_flow_destination_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='origin_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_flows', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='origin_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
