# Generated by Django 5.1.3 on 2024-11-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0009_alter_flow_origin_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('stations', models.ManyToManyField(related_name='station_groups', to='railbrowser.station')),
            ],
        ),
    ]
