# Generated by Django 5.1.3 on 2024-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0011_station_crs_code_station_pte_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='uic_code',
            field=models.CharField(default=1, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
