# Generated by Django 5.1.3 on 2024-11-24 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0014_stationgroup_nlc_code_alter_stationgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='destination_object_id',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='origin_object_id',
        ),
        migrations.AddField(
            model_name='flow',
            name='destination_global_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='origin_global_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stationcluster',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='stationgroup',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
