# Generated by Django 5.1.3 on 2024-11-24 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0015_remove_flow_destination_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
