# Generated by Django 5.1.3 on 2024-11-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0017_flow_source_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationcluster',
            name='station_groups',
            field=models.ManyToManyField(related_name='clusters', to='railbrowser.stationgroup'),
        ),
    ]
