# Generated by Django 5.1.3 on 2024-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0019_stationgroup_shadow_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='destination_object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='origin_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
