# Generated by Django 5.1.3 on 2024-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0020_flow_destination_object_id_flow_origin_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(blank=True, max_length=16, null=True)),
                ('atb_desc_1', models.CharField(blank=True, max_length=35, null=True)),
                ('atb_desc_2', models.CharField(blank=True, max_length=35, null=True)),
                ('atb_desc_3', models.CharField(blank=True, max_length=35, null=True)),
                ('atb_desc_4', models.CharField(blank=True, max_length=35, null=True)),
                ('cc_desc', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
