# Generated by Django 5.1.3 on 2024-11-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0021_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='railbrowser.route'),
        ),
    ]
