# Generated by Django 5.1.3 on 2024-11-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0022_flow_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fares', to='railbrowser.restriction'),
        ),
    ]
