# Generated by Django 5.1.3 on 2024-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0023_fare_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='restriction',
            name='cf_mkr',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='restriction',
            name='change_ind',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='restriction',
            name='description_out',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restriction',
            name='description_rtn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restriction',
            name='type_in',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='restriction',
            name='type_out',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
