# Generated by Django 5.1.3 on 2024-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0025_rename_end_time_timerestriction_time_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerestrictiondateband',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timerestrictiondateband',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timerestrictiondateband',
            name='time_code',
        ),
        migrations.AddField(
            model_name='timerestrictiondateband',
            name='cf_mkr',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='timerestrictiondateband',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerestrictiondateband',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerestrictiondateband',
            name='out_ret',
            field=models.CharField(choices=[('O', 'Out'), ('R', 'Return')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerestrictiondateband',
            name='sequence_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
