# Generated by Django 5.1.3 on 2024-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0027_remove_timerestrictiondateband_cf_mkr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrictiondateband',
            old_name='end_date',
            new_name='date_from',
        ),
        migrations.RemoveField(
            model_name='restrictiondateband',
            name='start_date',
        ),
        migrations.AddField(
            model_name='restrictiondateband',
            name='cf_mkr',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='restrictiondateband',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restrictiondateband',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
