# Generated by Django 5.1.3 on 2024-12-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0030_restrictionroutelocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrictionroutelocation',
            old_name='station',
            new_name='location',
        ),
    ]
