# Generated by Django 5.1.3 on 2024-12-03 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbrowser', '0031_rename_station_restrictionroutelocation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRestrictionTOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toc_code', models.CharField(blank=True, max_length=2, null=True)),
                ('time_restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tocs', to='railbrowser.timerestriction')),
            ],
        ),
    ]
